'use client'

import Link from 'next/link'
import { BarChart3, ChevronDown, LayoutDashboard, Menu, Package, ShoppingBag } from 'lucide-react'
import { usePathname } from 'next/navigation'

const links = [{ href: '/dashboard', label: 'Resumen', icon: LayoutDashboard }, { href: '/dashboard/sales', label: 'Ventas', icon: BarChart3 }, { href: '/dashboard/orders', label: 'Pedidos', icon: ShoppingBag }, { href: '/dashboard/products', label: 'Productos', icon: Package }]

export function DashboardNav() {
    const pathname = usePathname()
    return <header className="border-b border-[#DCE5F3] bg-white/90 backdrop-blur"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/dashboard" className="flex items-center gap-2.5 text-lg font-black tracking-[-.04em] text-[#12234A]"><span className="grid size-8 place-items-center rounded-[10px] bg-[#1E40AF] text-sm text-white shadow-[0_7px_16px_rgb(30_64_175_/_0.2)]">P</span>Pedilo</Link><nav className="hidden items-center gap-1 md:flex" aria-label="Navegación principal">{links.map((link) => { const Icon = link.icon; const active = link.href === '/dashboard' ? pathname === link.href : pathname.startsWith(link.href); return <Link key={link.href} href={link.href} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold transition ${active ? 'bg-[#EAF0FF] text-[#1E40AF]' : 'text-[#65738A] hover:bg-[#F5F8FC] hover:text-[#1E40AF]'}`}><Icon className="size-4" />{link.label}</Link> })}</nav><div className="flex items-center gap-3"><Link href="/create-menu" className="hidden items-center gap-1.5 rounded-lg border border-[#C9D7EA] px-3 py-2 text-xs font-semibold text-[#243556] transition hover:border-[#9EB3D8] hover:bg-[#F5F8FC] hover:text-[#1E40AF] sm:inline-flex"><Menu className="size-3.5" />Editar menú</Link><button type="button" className="flex items-center gap-2 rounded-full border border-[#DCE5F3] bg-white py-1.5 pl-1.5 pr-2.5 text-xs font-semibold text-[#12234A]"><span className="grid size-7 place-items-center rounded-full bg-[#D5E1FF] text-[#1C3A96]">JR</span><span className="hidden sm:block">Jorge</span><ChevronDown className="size-3.5 text-[#8996A9]" /></button></div></div><nav className="flex gap-1 overflow-x-auto px-5 pb-3 md:hidden" aria-label="Navegación móvil">{links.map((link) => <Link key={link.href} href={link.href} className={`whitespace-nowrap rounded-lg px-3 py-1.5 text-xs font-semibold ${pathname === link.href ? 'bg-[#EAF0FF] text-[#1E40AF]' : 'text-[#65738A] hover:bg-[#F5F8FC] hover:text-[#1E40AF]'}`}>{link.label}</Link>)}</nav></header>
}
